ADAPTER_KIND = "NSXIvS"
ADAPTER_NAME = "NSX IvS"
HOST_IDENTIFIER = "host"
PORT_IDENTIFIER = "port"
USER_CREDENTIAL = "vcenter_username"
PASSWORD_CREDENTIAL = "vcenter_password"
VCENTER_ADAPTER_KIND = "VMWARE"
SSH_COMMAND_TIMEOUT = 10